### ISSUE TITLE
Tracking Iteration 2023-11

### ISSUE THREAD

**Issue by ShiKaiWi** [CeresDB/horaedb#1291]
## Ease to use
- [x] Improve the success rate for creating new table @ZuLiangWang @ShiKaiWi 
	- [x] #1286 
	- [x] https://github.com/CeresDB/ceresmeta/pull/264
- [ ] Avoid the primary key duplicate error when use obkv wal implementation @ShiKaiWi  #1205
- [ ] Supports idempotence and retry of table creation and deletion. @ZuLiangWang 

### Write
- [ ] Better load balance according to the actual load of ceresdb-servers @ShiKaiWi 
- [x] Reduce the payload size written to the wal by support columnar encoding and compression @ShiKaiWi #1179 
- [ ] Improve the write performance when massive tables exist @ShiKaiWi  #1281 

### Query
- [ ] Separate the resources used by the queries involving different amount of data @jiacai2050 https://github.com/CeresDB/horaedb/pull/1303
- [ ] Cache the arrow payload in the memory or on the disk instead of the parquet payload to reduce the frequent decoding cost @jiacai2050 @Rachelint 
- [ ] Use a read-friendly format for the data in the immutable memtable to reduce the encoding cost during frequent queries @Rachelint 

## Features
- [ ] Support `use <database>` statement @chunshao90 
- [ ] Support analyze sql for distributed query @baojinri 
- [ ] Support query by opentsdb @baojinri https://github.com/CeresDB/horaedb/pull/1284

## Docs
- [ ] Update the docs for some new features, e.g. partition table.
- [ ] Design docs for the distributed query @Rachelint

**Comment by tanruixiang** [comment]
If there are any ideas, feel free to bring them up in the issue.
